### ISSUE TITLE
Change Loop Type After Creation

### ISSUE THREAD

**Issue by retroswan** [Silent-Tower-Games/fpsloop#1]
Loop type is set on creation of the `FPSLoop` object, but it can't be changed mid-loop.

Theoretically, you should just be able to change the type variable at any time & it will just start working. However, the variable is not exposed to users of the lib.

A good proposal in my opinion is a `FPSLoop_SetLoopType(FPSLoop_Type)` function.

**Comment by NCatalani** [comment]
Hey @retroswan, is there something wrong conceptually with my PR?
